# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-02-18 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_DefaultBuyPriceIzZero'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Was the subscription reminder notification sent'),
        ),
    ]
